payload:
- DST-PORT,5200
- DST-PORT,5201
- DST-PORT,3478
- DOMAIN-SUFFIX,openwrt
- GEOSITE,youku
- DOMAIN-SUFFIX,baidu.com
- DOMAIN-SUFFIX,chinamobile.com
- DOMAIN-SUFFIX,is.gd
- DOMAIN-KEYWORD,letsencrypt.org
- DOMAIN-SUFFIX,926123.tv
- DOMAIN-SUFFIX,zhibodou.com
- DOMAIN-SUFFIX,xib.cc
- DOMAIN-SUFFIX,sportsteam668.com
- DOMAIN-SUFFIX,sportsteam363.com
- DOMAIN-SUFFIX,zzzb324.com
- DOMAIN-SUFFIX,926001.tv
- DOMAIN-SUFFIX,926002.tv
- DOMAIN-SUFFIX,926003.tv
- DOMAIN-SUFFIX,515003.tv
- DOMAIN-SUFFIX,sportsteam356.com
- DOMAIN-SUFFIX,bdstatic.com
- DOMAIN-SUFFIX,yumixiu768.com
- DOMAIN-SUFFIX,zhibo1.cc
- DOMAIN-SUFFIX,jiatianxiazhuangshi.com
- DOMAIN-SUFFIX,xzbonlinepull.pq8.co
- DOMAIN-SUFFIX,125700.shop
- DOMAIN-SUFFIX,prdasbb18a1.com
- DOMAIN-SUFFIX,mayizhibo.net
- DOMAIN-SUFFIX,zzzb393.com
- DOMAIN-SUFFIX,hhz.pgw.jp
#- DOMAIN-SUFFIX,136605.xyz
- DOMAIN-SUFFIX,zhtcl.mydns.bz
- DOMAIN-SUFFIX,zhtcl.com
- DOMAIN-SUFFIX,imasdk.googleapis.com
- DOMAIN-SUFFIX,ntp.aliyun.com
- DOMAIN-SUFFIX,qqqrqq.com
- DOMAIN-SUFFIX,feijing-xzbonlinepull.17kq.fun
- DOMAIN-SUFFIX,ip.164746.xyz
- DOMAIN-SUFFIX,ii-587.wwentua.com
- DOMAIN-SUFFIX,miniprogram.lnitv.com
- DOMAIN-SUFFIX,bxtv.757888.xyz
- DOMAIN-KEYWORD,tyyszy
- DOMAIN-SUFFIX,rsfcxq.com
- DOMAIN-SUFFIX,bfzyapi.com
- DOMAIN-SUFFIX,miui.com
- DOMAIN-SUFFIX,time.windows.com
- DOMAIN-SUFFIX,pool.ntp.org
- DOMAIN-SUFFIX,v6.sync.afraid.org
- DOMAIN-SUFFIX,live.com
- DOMAIN-SUFFIX,live.net
- DOMAIN-SUFFIX,login.microsoftonline.com
